<?php

/**
 * BaseDaystat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $day
 * @property integer $task_id
 * @property integer $minutes
 * @property Task $Task
 * 
 * @method date    getDay()     Returns the current record's "day" value
 * @method integer getTaskId()  Returns the current record's "task_id" value
 * @method integer getMinutes() Returns the current record's "minutes" value
 * @method Task    getTask()    Returns the current record's "Task" value
 * @method Daystat setDay()     Sets the current record's "day" value
 * @method Daystat setTaskId()  Sets the current record's "task_id" value
 * @method Daystat setMinutes() Sets the current record's "minutes" value
 * @method Daystat setTask()    Sets the current record's "Task" value
 * 
 * @package    boetticher
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDaystat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('daystat');
        $this->hasColumn('day', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('minutes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}