<?php

/**
 * BaseUow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property integer $task_id
 * @property Task $Task
 * 
 * @method timestamp getStartTime()  Returns the current record's "start_time" value
 * @method timestamp getEndTime()    Returns the current record's "end_time" value
 * @method integer   getTaskId()     Returns the current record's "task_id" value
 * @method Task      getTask()       Returns the current record's "Task" value
 * @method Uow       setStartTime()  Sets the current record's "start_time" value
 * @method Uow       setEndTime()    Sets the current record's "end_time" value
 * @method Uow       setTaskId()     Sets the current record's "task_id" value
 * @method Uow       setTask()       Sets the current record's "Task" value
 * 
 * @package    boetticher
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('uow');
        $this->hasColumn('start_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}