<?php

/**
 * TaskGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaskGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaskGroup');
    }
}