<?php

/**
 * UowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UowTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object UowTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Uow');
  }

  public static function getActiveUow($user_id)
  {
    // Doctrine
    $uow = Doctrine_Query::create()->
      from('Uow u')->
      leftJoin('u.Task t')->
      leftJoin('t.TaskGroup g')->
      where('g.user_id = ?', array($user_id))->
      addWhere('u.end_time IS NULL')->
      fetchOne();
    return $uow;
  }

}
