# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: task, action: index }

task_start:
  url:   /task-start/:id
  param: { module: task, action: start }

task_stop:
  url:   /task-stop/:id
  param: { module: task, action: stop }

task_edit_visible:
  url:   /task-visibility
  param: { module: task, action: visible }

task_edit:
  url:   /task-edit/:id
  param: { module: task, action: edit }

task_new:
  url:   /task-new/:id
  param: { module: task, action: new }

group_edit:
  url:   /group-edit/:id
  param: { module: task, action: edit }

group_new:
  url:   /group-new/:id
  param: { module: task, action: new }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

