TaskGroup:
  columns:
    name: { type: string(255), notnull: true}
    user_id: { type: integer, notnull: true}
    hidden: { type: boolean, default: false}
  relations:
    sfGuardUser:
      local: user_id
      foreign: id
      foreignAlias: Groups
      onDelete: CASCADE

Task:
  columns:
    name: { type: string(255), notnull: true}
    color: { type: string(6), notnull: true}
    taskgroup_id: {type: integer, notnull: true}
    hidden: { type: boolean, default: false}
  relations:
    TaskGroup:
      local: taskgroup_id
      foreign: id
      foreignAlias: Tasks
      onDelete: CASCADE

Uow:
  columns:
    start_time: {type: timestamp, notnull: true}
    end_time: {type: timestamp}
    task_id: {type: integer, notnull: true}
  relations:
    Task:
      local: task_id
      foreign: id
      foreignAlias: Uows
      onDelete: CASCADE

Daystat:
  columns:
    day: {type: date, notnull: true}
    task_id: {type: integer, notnull: true}
    minutes: {type: integer, notnull: true}
  relations:
    Task:
      local: task_id
      foreign: id
      foreignAlias: Daystats
      onDelete: CASCADE

